import AppKit
import CryptoKit
import ImageIO

/// 一覧に出す代表の種類（F-01）。
enum ClipKind: String, CaseIterable {
    case text, richText, image, file, url, color, office, formula

    var label: String {
        switch self {
        case .text: "テキスト"
        case .richText: "書式付き"
        case .image: "画像"
        case .file: "ファイル"
        case .url: "リンク"
        case .color: "色"
        case .office: "オブジェクト"
        case .formula: "数式"
        }
    }

    var symbolName: String {
        switch self {
        case .text: "doc.plaintext"
        case .richText: "textformat"
        case .image: "photo"
        case .file: "doc"
        case .url: "link"
        case .color: "paintpalette"
        case .office: "square.on.circle"
        case .formula: "function"
        }
    }
}

/// 1つの型とそのデータ。
struct Representation: Equatable {
    let type: String
    let data: Data
}

/// 1回のコピーの中身。NSPasteboardItem ごとに、元のアプリが載せた順の型とデータをそのまま持つ。
struct Capture {
    var items: [[Representation]]
    var sourceBundleID: String?
    var sourceAppName: String?
    var date = Date()
    /// 読み取った時点で作るプレーンテキスト（HTMLからの変換はメインスレッドでしかできないため）。
    var plainText: String?
    /// 数式の元の式。自分の型か、画像に埋め込んだ目印から読む（F-06）。
    var latex: LatexSource?

    /// 自分がクリップボードに書いたものの印。履歴に二重に入れない。
    static let ownType = "io.github.kobito-tools.pastephant.own"
    static let latexType = "io.github.kobito-tools.pastephant.latex"
    /// パスワード管理アプリなどが付ける「保存しないで」の印（nspasteboard.org の取り決め）。
    static let privacyMarkers: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]

    static let plainTextType = NSPasteboard.PasteboardType.string.rawValue
    static let fileURLType = NSPasteboard.PasteboardType.fileURL.rawValue
    static let colorType = NSPasteboard.PasteboardType.color.rawValue
    static let richTextTypes: Set<String> = [NSPasteboard.PasteboardType.rtf.rawValue, NSPasteboard.PasteboardType.rtfd.rawValue, NSPasteboard.PasteboardType.html.rawValue, "com.apple.flat-rtfd"]
    static let imageTypes = ["public.png", "public.tiff", "public.jpeg", "public.heic", "com.compuserve.gif", "com.adobe.pdf"]

    // MARK: - 読み取り

    /// クリップボードの全ての項目・型を読む。メインスレッドで呼ぶ。
    static func read(from pasteboard: NSPasteboard, sourceBundleID: String? = nil, sourceAppName: String? = nil) -> Capture? {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else { return nil }
        var items: [[Representation]] = []
        for item in pasteboardItems {
            var representations: [Representation] = []
            for type in item.types {
                // 読めない型（遅延提供に失敗したものなど）と空のデータは飛ばす。
                guard let data = item.data(forType: type), !data.isEmpty || type.rawValue == Capture.ownType || privacyMarkers.contains(type.rawValue) else { continue }
                representations.append(Representation(type: type.rawValue, data: data))
            }
            if !representations.isEmpty { items.append(representations) }
        }
        guard !items.isEmpty else { return nil }
        var capture = Capture(items: items, sourceBundleID: sourceBundleID, sourceAppName: sourceAppName)
        capture.latex = capture.extractLatex()
        capture.plainText = capture.extractPlainText() ?? capture.latex?.source
        return capture
    }

    var allTypes: Set<String> { Set(items.flatMap { $0.map(\.type) }) }

    var totalBytes: Int { items.reduce(0) { $0 + $1.reduce(0) { $0 + $1.data.count } } }

    func data(for type: String) -> Data? {
        for item in items { if let found = item.first(where: { $0.type == type }) { return found.data } }
        return nil
    }

    var isPrivate: Bool { !allTypes.isDisjoint(with: Self.privacyMarkers) }
    var isOwn: Bool { allTypes.contains(Self.ownType) }

    // MARK: - 中身の判定

    static func sha256(_ data: Data) -> String { SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined() }

    /// 全ての項目・型・データから作るハッシュ。同じコピーなら同じ値になる。
    var contentHash: String {
        var hasher = SHA256()
        for (index, item) in items.enumerated() {
            for representation in item {
                hasher.update(data: Data("\(index)\t\(representation.type)\t\(Self.sha256(representation.data))\n".utf8))
            }
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    private func extractPlainText() -> String? {
        let texts = items.compactMap { item -> String? in
            if let data = item.first(where: { $0.type == Self.plainTextType })?.data { return String(data: data, encoding: .utf8) }
            if let data = item.first(where: { $0.type == NSPasteboard.PasteboardType.rtf.rawValue })?.data {
                return NSAttributedString(rtf: data, documentAttributes: nil)?.string
            }
            if let data = item.first(where: { $0.type == NSPasteboard.PasteboardType.html.rawValue })?.data, Thread.isMainThread {
                return NSAttributedString(html: data, documentAttributes: nil)?.string
            }
            return nil
        }
        let joined = texts.joined(separator: "\n")
        return joined.isEmpty ? nil : joined
    }

    /// 自分の型（JSON）、PNG の説明、PDF のキーワードの順に探す。
    private func extractLatex() -> LatexSource? {
        if let data = data(for: Self.latexType), let json = String(data: data, encoding: .utf8), let latex = LatexSource(json: json) { return latex }
        if let png = data(for: "public.png"), let source = CGImageSourceCreateWithData(png as CFData, nil),
           let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
           let png = properties[kCGImagePropertyPNGDictionary] as? [CFString: Any],
           let description = png[kCGImagePropertyPNGDescription] as? String, let latex = LatexSource(embedded: description) { return latex }
        if let pdf = data(for: "com.adobe.pdf"), let provider = CGDataProvider(data: pdf as CFData), let document = CGPDFDocument(provider), let info = document.info {
            var keywords: CGPDFStringRef?
            if CGPDFDictionaryGetString(info, "Keywords", &keywords), let keywords, let text = CGPDFStringCopyTextString(keywords) as String?, let latex = LatexSource(embedded: text) { return latex }
        }
        return nil
    }

    var fileURLs: [URL] {
        items.compactMap { item in
            item.first(where: { $0.type == Self.fileURLType }).flatMap { String(data: $0.data, encoding: .utf8) }.flatMap(URL.init(string:))
        }
    }

    var imageData: Data? {
        for type in Self.imageTypes { if let data = data(for: type) { return data } }
        return nil
    }

    var kind: ClipKind {
        let types = allTypes
        if latex != nil || types.contains(Self.latexType) { return .formula }
        if types.contains(where: Self.isOfficeType) { return .office }
        if types.contains(Self.fileURLType) { return .file }
        if types.contains(Self.colorType), plainText == nil { return .color }
        if plainText == nil { return imageData != nil ? .image : .office }
        if let text = plainText, Self.isSingleURL(text) { return .url }
        if !types.isDisjoint(with: Self.richTextTypes) { return .richText }
        return .text
    }

    /// パワポ・Excel・Keynote などの独自の型。Word の文章は書式付きテキストとして扱う。
    static func isOfficeType(_ type: String) -> Bool {
        ["PowerPoint", "Excel", "com.apple.iWork", "com.apple.keynote", "com.apple.Keynote", "com.apple.numbers", "com.apple.freeform"].contains { type.contains($0) }
    }

    static func isSingleURL(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              let url = URL(string: trimmed), let scheme = url.scheme?.lowercased() else { return false }
        return ["http", "https", "ftp", "mailto", "file"].contains(scheme)
    }

    var fileNames: String? {
        let names = fileURLs.map { $0.lastPathComponent }
        return names.isEmpty ? nil : names.joined(separator: "\n")
    }

    /// 一覧に出す短い文字。
    var preview: String {
        switch kind {
        case .file:
            return fileNames?.replacingOccurrences(of: "\n", with: ", ") ?? "ファイル"
        case .image:
            if let size = imageData.flatMap(Self.pixelSize) { return "画像 \(size.width)×\(size.height)" }
            return "画像"
        case .color:
            return "色"
        case .formula:
            return latex.map { Self.shorten($0.source) } ?? "数式"
        case .office where plainText == nil:
            return "\(sourceAppName ?? "アプリ") のオブジェクト"
        default:
            return plainText.map(Self.shorten) ?? ""
        }
    }

    /// 空白と改行をまとめて、先頭の300文字にする。
    static func shorten(_ text: String) -> String {
        let collapsed = text.split(whereSeparator: { $0.isWhitespace || $0.isNewline }).joined(separator: " ")
        return collapsed.count > 300 ? String(collapsed.prefix(300)) + "…" : collapsed
    }

    // MARK: - 画像

    static func pixelSize(_ data: Data) -> (width: Int, height: Int)? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int, let height = properties[kCGImagePropertyPixelHeight] as? Int else { return nil }
        return (width, height)
    }

    /// 一覧用のサムネ（長い辺が maxPixels のPNG）。どのスレッドからでも呼べる。
    func makeThumbnail(maxPixels: Int = 320) -> Data? {
        guard let data = imageData else { return nil }
        let image: CGImage?
        if data.starts(with: Array("%PDF".utf8)) {
            image = Self.renderPDF(data, maxPixels: maxPixels)
        } else if let source = CGImageSourceCreateWithData(data as CFData, nil) {
            let options: [CFString: Any] = [kCGImageSourceCreateThumbnailFromImageAlways: true, kCGImageSourceThumbnailMaxPixelSize: maxPixels, kCGImageSourceCreateThumbnailWithTransform: true]
            image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary)
        } else {
            image = nil
        }
        guard let image else { return nil }
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(output, "public.png" as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        return CGImageDestinationFinalize(destination) ? output as Data : nil
    }

    private static func renderPDF(_ data: Data, maxPixels: Int) -> CGImage? {
        guard let provider = CGDataProvider(data: data as CFData), let document = CGPDFDocument(provider), let page = document.page(at: 1) else { return nil }
        let box = page.getBoxRect(.cropBox)
        guard box.width > 0, box.height > 0 else { return nil }
        let scale = CGFloat(maxPixels) / max(box.width, box.height)
        let width = max(1, Int(box.width * scale)), height = max(1, Int(box.height * scale))
        guard let context = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0, space: CGColorSpaceCreateDeviceRGB(), bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return nil }
        context.scaleBy(x: scale, y: scale)
        context.translateBy(x: -box.minX, y: -box.minY)
        context.drawPDFPage(page)
        return context.makeImage()
    }
}
